<?php

namespace Database\Seeders;

use App\Models\Categoria;
use App\Models\Destino;
use Illuminate\Database\Seeder;

class DestinoSeeder extends Seeder
{
    public function run(): void
    {
        $playas = Categoria::where('nombre', 'Playas')->first();
        $naturaleza = Categoria::where('nombre', 'Montañas y naturaleza')->first();
        $restaurantes = Categoria::where('nombre', 'Restaurantes')->first();
        $hoteles = Categoria::where('nombre', 'Hoteles')->first();
        $recreativos = Categoria::where('nombre', 'Centros recreativos')->first();
        $culturales = Categoria::where('nombre', 'Sitios culturales')->first();

        $destinos = [
            [
                'categoria_id' => $playas?->id,
                'nombre' => 'Playa El Tunco',
                'descripcion' => 'Uno de los destinos de playa más populares de El Salvador, conocido por su ambiente juvenil, surf, atardeceres y vida nocturna.',
                'ubicacion' => 'Tamanique, La Libertad',
                'departamento' => 'La Libertad',
                'municipio' => 'Tamanique',
                'direccion' => 'Zona costera del departamento de La Libertad',
                'contacto' => 'Información turística local',
                'telefono' => '2600-0101',
                'sitio_web' => null,
                'imagen' => 'img/destinos/tunco.jpg',
                'costo_estimado' => 15.00,
                'dias_atencion' => 'Sábado y domingo',
                'hora_apertura' => '12:48',
                'hora_cierre' => '05:50',
                'horario' => 'Abierto todos los días',
                'recomendaciones' => 'Llevar ropa cómoda, protector solar y efectivo para consumo local.',
                'estado' => true,
                'latitud' => 13.4942000,
                'longitud' => -89.3812000,
            ],
            [
                'categoria_id' => $naturaleza?->id,
                'nombre' => 'Volcán El Boquerón',
                'descripcion' => 'Parque natural ubicado en San Salvador, famoso por su cráter, clima fresco y senderos accesibles para visitantes.',
                'ubicacion' => 'San Salvador',
                'departamento' => 'San Salvador',
                'municipio' => 'San Salvador',
                'direccion' => 'Parque Nacional El Boquerón',
                'contacto' => 'Administración del parque',
                'telefono' => '2600-0102',
                'sitio_web' => null,
                'imagen' => 'img/destinos/boqueron.jpg',
                'costo_estimado' => 5.00,
                'dias_atencion' => 'Todos los días',
                'hora_apertura' => '08:00',
                'hora_cierre' => '17:00',
                'horario' => '8:00 a.m. - 5:00 p.m.',
                'recomendaciones' => 'Usar zapatos cómodos y llevar abrigo ligero por el clima fresco.',
                'estado' => true,
                'latitud' => 13.7340000,
                'longitud' => -89.2870000,
            ],
            [
                'categoria_id' => $culturales?->id,
                'nombre' => 'Suchitoto',
                'descripcion' => 'Pueblo turístico reconocido por sus calles empedradas, arquitectura colonial, arte, cultura y vista al lago Suchitlán.',
                'ubicacion' => 'Cuscatlán',
                'departamento' => 'Cuscatlán',
                'municipio' => 'Suchitoto',
                'direccion' => 'Centro histórico de Suchitoto',
                'contacto' => 'Información turística municipal',
                'telefono' => '2600-0103',
                'sitio_web' => null,
                'imagen' => 'img/destinos/suchitoto.jpg',
                'costo_estimado' => 20.00,
                'dias_atencion' => 'Todos los días',
                'hora_apertura' => null,
                'hora_cierre' => null,
                'horario' => 'Abierto todos los días',
                'recomendaciones' => 'Ideal para caminar, tomar fotografías y degustar comida típica.',
                'estado' => true,
                'latitud' => 13.9381000,
                'longitud' => -89.0278000,
            ],
            [
                'categoria_id' => $culturales?->id,
                'nombre' => 'Joya de Cerén',
                'descripcion' => 'Sitio arqueológico declarado Patrimonio de la Humanidad, conocido como la Pompeya de América.',
                'ubicacion' => 'La Libertad',
                'departamento' => 'La Libertad',
                'municipio' => 'San Juan Opico',
                'direccion' => 'San Juan Opico, La Libertad',
                'contacto' => 'Administración del sitio arqueológico',
                'telefono' => '2600-0104',
                'sitio_web' => null,
                'imagen' => 'img/destinos/joya-de-ceren.jpg',
                'costo_estimado' => 3.00,
                'dias_atencion' => 'Todos los días',
                'hora_apertura' => '07:00',
                'hora_cierre' => '16:53',
                'horario' => '9:00 a.m. - 4:00 p.m.',
                'recomendaciones' => 'Consultar horarios actualizados antes de visitar.',
                'estado' => true,
                'latitud' => 13.8277000,
                'longitud' => -89.3603000,
            ],
            [
                'categoria_id' => $naturaleza?->id,
                'nombre' => 'Lago de Coatepeque',
                'descripcion' => 'Lago de origen volcánico reconocido por sus aguas azuladas, restaurantes, miradores y actividades acuáticas.',
                'ubicacion' => 'Santa Ana',
                'departamento' => 'Santa Ana',
                'municipio' => 'El Congo / Coatepeque',
                'direccion' => 'Municipios de El Congo y Coatepeque',
                'contacto' => 'Información turística local',
                'telefono' => '2600-0105',
                'sitio_web' => null,
                'imagen' => 'img/destinos/coatepeque.jpg',
                'costo_estimado' => 25.85,
                'dias_atencion' => 'Todos los días',
                'hora_apertura' => null,
                'hora_cierre' => null,
                'horario' => 'Abierto todos los días',
                'recomendaciones' => 'Reservar con anticipación si se visitan restaurantes o alojamientos.',
                'estado' => true,
                'latitud' => 13.8643000,
                'longitud' => -89.5450000,
            ],
            [
                'categoria_id' => $playas?->id,
                'nombre' => 'Playa El Cuco',
                'descripcion' => 'Playa reconocida de la zona oriental de El Salvador, ideal para descanso, turismo familiar y gastronomía local.',
                'ubicacion' => 'Chirilagua, San Miguel',
                'departamento' => 'San Miguel',
                'municipio' => 'Chirilagua',
                'direccion' => 'Zona costera de Playa El Cuco, Chirilagua, San Miguel.',
                'contacto' => 'Información turística local',
                'telefono' => '2600-0001',
                'sitio_web' => null,
                'imagen' => 'images/elcuco_real.png',
                'costo_estimado' => 15.00,
                'dias_atencion' => 'Todos los días',
                'hora_apertura' => '07:00',
                'hora_cierre' => '18:00',
                'horario' => null,
                'recomendaciones' => 'Llevar protector solar, ropa cómoda y visitar durante la mañana.',
                'estado' => true,
                'latitud' => 13.1739000,
                'longitud' => -88.1078000,
            ],
            [
                'categoria_id' => $naturaleza?->id,
                'nombre' => 'Volcán Chaparrastique',
                'descripcion' => 'Uno de los volcanes más representativos de la zona oriental, atractivo para visitantes interesados en naturaleza y paisajes.',
                'ubicacion' => 'San Miguel',
                'departamento' => 'San Miguel',
                'municipio' => 'San Miguel',
                'direccion' => 'Área del Volcán Chaparrastique, San Miguel.',
                'contacto' => 'Información turística municipal',
                'telefono' => '2600-0002',
                'sitio_web' => null,
                'imagen' => 'images/chaparrastique_real.png',
                'costo_estimado' => 10.00,
                'dias_atencion' => 'Todos los días',
                'hora_apertura' => '06:00',
                'hora_cierre' => '16:00',
                'horario' => null,
                'recomendaciones' => 'Usar calzado adecuado, llevar agua y verificar condiciones climáticas antes de visitar.',
                'estado' => true,
                'latitud' => 13.4347000,
                'longitud' => -88.2697000,
            ],
            [
                'categoria_id' => $naturaleza?->id,
                'nombre' => 'Laguna de Alegría',
                'descripcion' => 'Destino natural ubicado en Usulután, conocido por sus paisajes, clima agradable y valor turístico.',
                'ubicacion' => 'Alegría, Usulután',
                'departamento' => 'Usulután',
                'municipio' => 'Alegría',
                'direccion' => 'Laguna de Alegría, municipio de Alegría, Usulután.',
                'contacto' => 'Información turística de Alegría',
                'telefono' => '2600-0003',
                'sitio_web' => null,
                'imagen' => 'images/alegria_real.png',
                'costo_estimado' => 8.00,
                'dias_atencion' => 'Todos los días',
                'hora_apertura' => '07:00',
                'hora_cierre' => '17:00',
                'horario' => null,
                'recomendaciones' => 'Ideal para fotografía, caminatas y turismo familiar.',
                'estado' => true,
                'latitud' => 13.5069000,
                'longitud' => -88.4856000,
            ],
            [
                'categoria_id' => $playas?->id,
                'nombre' => 'Golfo de Fonseca',
                'descripcion' => 'Zona costera compartida por El Salvador, Honduras y Nicaragua, reconocida por sus paisajes marítimos e islas.',
                'ubicacion' => 'La Unión',
                'departamento' => 'La Unión',
                'municipio' => 'La Unión',
                'direccion' => 'Zona costera del Golfo de Fonseca, La Unión.',
                'contacto' => 'Información turística local',
                'telefono' => '2600-0004',
                'sitio_web' => null,
                'imagen' => 'images/golfo_real.png',
                'costo_estimado' => 20.00,
                'dias_atencion' => 'Todos los días',
                'hora_apertura' => '07:00',
                'hora_cierre' => '17:00',
                'horario' => null,
                'recomendaciones' => 'Consultar disponibilidad de recorridos en lancha y llevar protección solar.',
                'estado' => true,
                'latitud' => 13.3369000,
                'longitud' => -87.8439000,
            ],
            [
                'categoria_id' => $recreativos?->id,
                'nombre' => 'Laguna Seca El Pacayal',
                'descripcion' => 'Centro recreativo ideal para convivencias familiares, descanso y actividades al aire libre.',
                'ubicacion' => 'San Miguel',
                'departamento' => 'San Miguel',
                'municipio' => 'San Miguel',
                'direccion' => 'Zona de El Pacayal, San Miguel.',
                'contacto' => 'Administración del centro recreativo',
                'telefono' => '2600-0005',
                'sitio_web' => null,
                'imagen' => 'images/pacayal_paisaje.png',
                'costo_estimado' => 12.00,
                'dias_atencion' => 'Sábado y domingo',
                'hora_apertura' => '08:00',
                'hora_cierre' => '17:00',
                'horario' => null,
                'recomendaciones' => 'Recomendado para visitas familiares y actividades recreativas.',
                'estado' => true,
                'latitud' => 13.4833000,
                'longitud' => -88.1833000,
            ],
            [
                'categoria_id' => $restaurantes?->id,
                'nombre' => 'Restaurante Mirador Oriental',
                'descripcion' => 'Restaurante turístico con comida típica salvadoreña y ambiente familiar.',
                'ubicacion' => 'San Miguel',
                'departamento' => 'San Miguel',
                'municipio' => 'San Miguel',
                'direccion' => 'Carretera Panamericana, San Miguel.',
                'contacto' => 'Atención al cliente',
                'telefono' => '2600-0002',
                'sitio_web' => 'https://www.facebook.com/',
                'imagen' => 'images/restaurante_mirador_oriental.jpg',
                'costo_estimado' => 18.00,
                'dias_atencion' => 'Martes a domingo',
                'hora_apertura' => '10:00',
                'hora_cierre' => '21:00',
                'horario' => null,
                'recomendaciones' => 'Ideal para almuerzos familiares y visitantes que buscan gastronomía local.',
                'estado' => true,
                'latitud' => 13.4830000,
                'longitud' => -88.1750000,
            ],
            [
                'categoria_id' => $hoteles?->id,
                'nombre' => 'Hotel Vista Azul',
                'descripcion' => 'Hotel turístico orientado a visitantes que buscan alojamiento cerca de la playa.',
                'ubicacion' => 'El Cuco, San Miguel',
                'departamento' => 'San Miguel',
                'municipio' => 'Chirilagua',
                'direccion' => 'Calle principal hacia Playa El Cuco, Chirilagua.',
                'contacto' => 'Recepción del hotel',
                'telefono' => '2600-0003',
                'sitio_web' => 'https://www.example.com',
                'imagen' => 'images/hotel_vista_azul.jpg',
                'costo_estimado' => 45.00,
                'dias_atencion' => 'Todos los días',
                'hora_apertura' => '00:00',
                'hora_cierre' => '23:59',
                'horario' => null,
                'recomendaciones' => 'Recomendado para visitantes que desean hospedarse cerca de la playa.',
                'estado' => true,
                'latitud' => 13.1760000,
                'longitud' => -88.1050000,
            ],
            [
                'categoria_id' => $culturales?->id,
                'nombre' => 'Centro Histórico de Alegría',
                'descripcion' => 'Zona cultural con arquitectura tradicional, gastronomía local y espacios para recorrer en familia.',
                'ubicacion' => 'Alegría, Usulután',
                'departamento' => 'Usulután',
                'municipio' => 'Alegría',
                'direccion' => 'Centro del municipio de Alegría, Usulután.',
                'contacto' => 'Casa de la cultura local',
                'telefono' => '2600-0008',
                'sitio_web' => null,
                'imagen' => 'images/centro_historico_alegria.jpeg',
                'costo_estimado' => 5.00,
                'dias_atencion' => 'Todos los días',
                'hora_apertura' => '08:00',
                'hora_cierre' => '18:00',
                'horario' => null,
                'recomendaciones' => 'Visitar el parque central, probar comida local y recorrer los alrededores.',
                'estado' => true,
                'latitud' => 13.5000000,
                'longitud' => -88.4833000,
            ],
            [
                'categoria_id' => $recreativos?->id,
                'nombre' => 'Hostal y Parque Acuático El Edén de Brizuela',
                'descripcion' => 'Este es uno de los destinos recreativos más recientes y populares en Nueva Guadalupe, ideal para quienes buscan refrescarse y pasar un día de relajación familiar. El lugar destaca por sus atractivas instalaciones acuáticas, que incluyen opciones para niños, una piscina semi-olímpica y la llamativa "piscina de la isla", cuyo diseño simula un pequeño montículo de tierra en el centro del agua. Además de los baños, el complejo ofrece una experiencia integral con servicio de restaurante especializado en platillos como churrascos, aves y mariscos a la plancha, área de bar, mesas de billar y espacios de descanso. Para quienes desean extender su visita, también cuenta con habitaciones de alojamiento, convirtiéndolo en un pequeño resort muy completo para los turistas.',
                'ubicacion' => 'Nueva Guadalupe, San Miguel',
                'departamento' => 'San Miguel',
                'municipio' => 'Nueva Guadalupe',
                'direccion' => 'Nueva Guadalupe, San Miguel.',
                'contacto' => 'Administración del parque',
                'telefono' => '2600-0000',
                'sitio_web' => null,
                'imagen' => 'images/eden_brizuela.jpg',
                'costo_estimado' => 5.00,
                'dias_atencion' => 'Todos los días',
                'hora_apertura' => '09:00',
                'hora_cierre' => '20:00',
                'horario' => null,
                'recomendaciones' => 'Llevar traje de baño y ropa cómoda. Ideal para familias.',
                'estado' => true,
                'latitud' => 13.5317600,
                'longitud' => -88.3506000,
            ],
            [
                'categoria_id' => $recreativos?->id,
                'nombre' => 'Turicentro Flor del Río',
                'descripcion' => 'Turicentro natural reconocido por sus refrescantes piscinas de agua de vertiente, rodeado de vegetación y espacios ideales para el descanso familiar. Es un destino popular para refrescarse durante el fin de semana.',
                'ubicacion' => 'Moncagua, San Miguel',
                'departamento' => 'San Miguel',
                'municipio' => 'Moncagua',
                'direccion' => 'Moncagua, San Miguel.',
                'contacto' => 'Administración del turicentro',
                'telefono' => '2600-0000',
                'sitio_web' => null,
                'imagen' => 'images/flor_del_rio.jpg',
                'costo_estimado' => 5.00,
                'dias_atencion' => 'Todos los días',
                'hora_apertura' => '08:00',
                'hora_cierre' => '17:00',
                'horario' => null,
                'recomendaciones' => 'Llevar traje de baño, protector solar y ropa cómoda.',
                'estado' => true,
                'latitud' => 13.6065700,
                'longitud' => -88.2545000,
            ],
        ];

        foreach ($destinos as $destino) {
            Destino::updateOrCreate(
                ['nombre' => $destino['nombre']],
                $destino
            );
        }
    }
}