<?php

namespace Database\Seeders;

use App\Models\Categoria;
use App\Models\Destino;
use Illuminate\Database\Seeder;

class DestinoSeeder extends Seeder
{
    public function run(): void
    {
        $playas = Categoria::where('nombre', 'Playas')->first();
        $naturaleza = Categoria::where('nombre', 'Montañas y naturaleza')->first();
        $restaurantes = Categoria::where('nombre', 'Restaurantes')->first();
        $hoteles = Categoria::where('nombre', 'Hoteles')->first();
        $recreativos = Categoria::where('nombre', 'Centros recreativos')->first();
        $culturales = Categoria::where('nombre', 'Sitios culturales')->first();

        $destinos = [
            [
                'categoria_id' => $playas?->id,
                'nombre' => 'Playa El Tunco',
                'nombre_en' => 'El Tunco Beach',
                'nombre_en' => 'El Tunco Beach',
                'descripcion' => 'Uno de los destinos de playa más populares de El Salvador, conocido por su ambiente juvenil, surf, atardeceres y vida nocturna.',
                'descripcion_en' => 'One of the most popular beach destinations in El Salvador, known for its youthful atmosphere, surfing, sunsets, and nightlife.',
                'ubicacion' => 'Tamanique, La Libertad',
                'ubicacion_en' => 'Tamanique, La Libertad',
                'departamento' => 'La Libertad',
                'municipio' => 'Tamanique',
                'direccion' => 'Zona costera del departamento de La Libertad',
                'contacto' => 'Información turística local',
                'contacto_en' => 'Local tourist information',
                'telefono' => '2600-0101',
                'sitio_web' => null,
                'imagen' => 'img/destinos/tunco.jpg',
                'costo_estimado' => 15.00,
                'dias_atencion' => 'Sábado y domingo',
                'dias_atencion_en' => 'Saturday and Sunday',
                'hora_apertura' => '12:48',
                'hora_cierre' => '05:50',
                'horario' => 'Abierto todos los días',
                'recomendaciones' => 'Llevar ropa cómoda, protector solar y efectivo para consumo local.',
                'recomendaciones_en' => 'Bring comfortable clothes, sunscreen, and cash for local consumption.',
                'estado' => true,
                'latitud' => 13.4942000,
                'longitud' => -89.3812000,
            ],
            [
                'categoria_id' => $naturaleza?->id,
                'nombre' => 'Volcán El Boquerón',
                'nombre_en' => 'El Boquerón Volcano',
                'nombre_en' => 'El Boquerón Volcano',
                'descripcion' => 'Parque natural ubicado en San Salvador, famoso por su cráter, clima fresco y senderos accesibles para visitantes.',
                'descripcion_en' => 'Natural park located in San Salvador, famous for its crater, cool climate, and accessible trails for visitors.',
                'ubicacion' => 'San Salvador',
                'ubicacion_en' => 'San Salvador',
                'departamento' => 'San Salvador',
                'municipio' => 'San Salvador',
                'direccion' => 'Parque Nacional El Boquerón',
                'contacto' => 'Administración del parque',
                'contacto_en' => 'Park administration',
                'telefono' => '2600-0102',
                'sitio_web' => null,
                'imagen' => 'img/destinos/boqueron.jpg',
                'costo_estimado' => 5.00,
                'dias_atencion' => 'Todos los días',
                'dias_atencion_en' => 'Every day',
                'hora_apertura' => '08:00',
                'hora_cierre' => '17:00',
                'horario' => '8:00 a.m. - 5:00 p.m.',
                'recomendaciones' => 'Usar zapatos cómodos y llevar abrigo ligero por el clima fresco.',
                'recomendaciones_en' => 'Wear comfortable shoes and bring a light jacket due to the cool weather.',
                'estado' => true,
                'latitud' => 13.7340000,
                'longitud' => -89.2870000,
            ],
            [
                'categoria_id' => $culturales?->id,
                'nombre' => 'Suchitoto',
                'nombre_en' => 'Suchitoto',
                'nombre_en' => 'Suchitoto',
                'descripcion' => 'Pueblo turístico reconocido por sus calles empedradas, arquitectura colonial, arte, cultura y vista al lago Suchitlán.',
                'descripcion_en' => 'Tourist town renowned for its cobblestone streets, colonial architecture, art, culture, and views of Lake Suchitlán.',
                'ubicacion' => 'Cuscatlán',
                'ubicacion_en' => 'Cuscatlán',
                'departamento' => 'Cuscatlán',
                'municipio' => 'Suchitoto',
                'direccion' => 'Centro histórico de Suchitoto',
                'contacto' => 'Información turística municipal',
                'contacto_en' => 'Municipal tourist information',
                'telefono' => '2600-0103',
                'sitio_web' => null,
                'imagen' => 'img/destinos/suchitoto.jpg',
                'costo_estimado' => 20.00,
                'dias_atencion' => 'Todos los días',
                'dias_atencion_en' => 'Every day',
                'hora_apertura' => null,
                'hora_cierre' => null,
                'horario' => 'Abierto todos los días',
                'recomendaciones' => 'Ideal para caminar, tomar fotografías y degustar comida típica.',
                'recomendaciones_en' => 'Ideal for walking, taking photos, and tasting local food.',
                'estado' => true,
                'latitud' => 13.9381000,
                'longitud' => -89.0278000,
            ],
            [
                'categoria_id' => $culturales?->id,
                'nombre' => 'Joya de Cerén',
                'nombre_en' => 'Joya de Cerén',
                'nombre_en' => 'Joya de Cerén',
                'descripcion' => 'Sitio arqueológico declarado Patrimonio de la Humanidad, conocido como la Pompeya de América.',
                'descripcion_en' => 'Archaeological site declared a World Heritage Site, known as the Pompeii of America.',
                'ubicacion' => 'La Libertad',
                'ubicacion_en' => 'La Libertad',
                'departamento' => 'La Libertad',
                'municipio' => 'San Juan Opico',
                'direccion' => 'San Juan Opico, La Libertad',
                'contacto' => 'Administración del sitio arqueológico',
                'contacto_en' => 'Archaeological site administration',
                'telefono' => '2600-0104',
                'sitio_web' => null,
                'imagen' => 'img/destinos/joya-de-ceren.jpg',
                'costo_estimado' => 3.00,
                'dias_atencion' => 'Todos los días',
                'dias_atencion_en' => 'Every day',
                'hora_apertura' => '07:00',
                'hora_cierre' => '16:53',
                'horario' => '9:00 a.m. - 4:00 p.m.',
                'recomendaciones' => 'Consultar horarios actualizados antes de visitar.',
                'recomendaciones_en' => 'Check updated hours before visiting.',
                'estado' => true,
                'latitud' => 13.8277000,
                'longitud' => -89.3603000,
            ],
            [
                'categoria_id' => $naturaleza?->id,
                'nombre' => 'Lago de Coatepeque',
                'nombre_en' => 'Lake Coatepeque',
                'nombre_en' => 'Lake Coatepeque',
                'descripcion' => 'Lago de origen volcánico reconocido por sus aguas azuladas, restaurantes, miradores y actividades acuáticas.',
                'descripcion_en' => 'Lake of volcanic origin known for its blue waters, restaurants, viewpoints, and water activities.',
                'ubicacion' => 'Santa Ana',
                'ubicacion_en' => 'Santa Ana',
                'departamento' => 'Santa Ana',
                'municipio' => 'El Congo / Coatepeque',
                'direccion' => 'Municipios de El Congo y Coatepeque',
                'contacto' => 'Información turística local',
                'contacto_en' => 'Local tourist information',
                'telefono' => '2600-0105',
                'sitio_web' => null,
                'imagen' => 'img/destinos/coatepeque.jpg',
                'costo_estimado' => 25.85,
                'dias_atencion' => 'Todos los días',
                'dias_atencion_en' => 'Every day',
                'hora_apertura' => null,
                'hora_cierre' => null,
                'horario' => 'Abierto todos los días',
                'recomendaciones' => 'Reservar con anticipación si se visitan restaurantes o alojamientos.',
                'recomendaciones_en' => 'Book in advance if visiting restaurants or accommodations.',
                'estado' => true,
                'latitud' => 13.8643000,
                'longitud' => -89.5450000,
            ],
            [
                'categoria_id' => $playas?->id,
                'nombre' => 'Playa El Cuco',
                'nombre_en' => 'El Cuco Beach',
                'nombre_en' => 'El Cuco Beach',
                'descripcion' => 'Playa reconocida de la zona oriental de El Salvador, ideal para descanso, turismo familiar y gastronomía local.',
                'descripcion_en' => 'Renowned beach in the eastern part of El Salvador, ideal for rest, family tourism, and local cuisine.',
                'ubicacion' => 'Chirilagua, San Miguel',
                'ubicacion_en' => 'Chirilagua, San Miguel',
                'departamento' => 'San Miguel',
                'municipio' => 'Chirilagua',
                'direccion' => 'Zona costera de Playa El Cuco, Chirilagua, San Miguel.',
                'contacto' => 'Información turística local',
                'contacto_en' => 'Local tourist information',
                'telefono' => '2600-0001',
                'sitio_web' => null,
                'imagen' => 'images/elcuco_real.png',
                'costo_estimado' => 15.00,
                'dias_atencion' => 'Todos los días',
                'dias_atencion_en' => 'Every day',
                'hora_apertura' => '07:00',
                'hora_cierre' => '18:00',
                'horario' => null,
                'recomendaciones' => 'Llevar protector solar, ropa cómoda y visitar durante la mañana.',
                'recomendaciones_en' => 'Bring sunscreen, comfortable clothes, and visit during the morning.',
                'estado' => true,
                'latitud' => 13.1739000,
                'longitud' => -88.1078000,
            ],
            [
                'categoria_id' => $naturaleza?->id,
                'nombre' => 'Volcán Chaparrastique',
                'nombre_en' => 'Chaparrastique Volcano',
                'nombre_en' => 'Chaparrastique Volcano',
                'descripcion' => 'Uno de los volcanes más representativos de la zona oriental, atractivo para visitantes interesados en naturaleza y paisajes.',
                'descripcion_en' => 'One of the most representative volcanoes in the eastern zone, attractive to visitors interested in nature and landscapes.',
                'ubicacion' => 'San Miguel',
                'ubicacion_en' => 'San Miguel',
                'departamento' => 'San Miguel',
                'municipio' => 'San Miguel',
                'direccion' => 'Área del Volcán Chaparrastique, San Miguel.',
                'contacto' => 'Información turística municipal',
                'contacto_en' => 'Municipal tourist information',
                'telefono' => '2600-0002',
                'sitio_web' => null,
                'imagen' => 'images/chaparrastique_real.png',
                'costo_estimado' => 10.00,
                'dias_atencion' => 'Todos los días',
                'dias_atencion_en' => 'Every day',
                'hora_apertura' => '06:00',
                'hora_cierre' => '16:00',
                'horario' => null,
                'recomendaciones' => 'Usar calzado adecuado, llevar agua y verificar condiciones climáticas antes de visitar.',
                'recomendaciones_en' => 'Wear appropriate footwear, bring water, and check weather conditions before visiting.',
                'estado' => true,
                'latitud' => 13.4347000,
                'longitud' => -88.2697000,
            ],
            [
                'categoria_id' => $naturaleza?->id,
                'nombre' => 'Laguna de Alegría',
                'nombre_en' => 'Alegría Lagoon',
                'nombre_en' => 'Alegría Lagoon',
                'descripcion' => 'Destino natural ubicado en Usulután, conocido por sus paisajes, clima agradable y valor turístico.',
                'descripcion_en' => 'Natural destination located in Usulután, known for its landscapes, pleasant climate, and tourist value.',
                'ubicacion' => 'Alegría, Usulután',
                'ubicacion_en' => 'Alegría, Usulután',
                'departamento' => 'Usulután',
                'municipio' => 'Alegría',
                'direccion' => 'Laguna de Alegría, municipio de Alegría, Usulután.',
                'contacto' => 'Información turística de Alegría',
                'contacto_en' => 'Información turística de Alegría',
                'telefono' => '2600-0003',
                'sitio_web' => null,
                'imagen' => 'images/alegria_real.png',
                'costo_estimado' => 8.00,
                'dias_atencion' => 'Todos los días',
                'dias_atencion_en' => 'Every day',
                'hora_apertura' => '07:00',
                'hora_cierre' => '17:00',
                'horario' => null,
                'recomendaciones' => 'Ideal para fotografía, caminatas y turismo familiar.',
                'recomendaciones_en' => 'Ideal for photography, hiking, and family tourism.',
                'estado' => true,
                'latitud' => 13.5069000,
                'longitud' => -88.4856000,
            ],
            [
                'categoria_id' => $playas?->id,
                'nombre' => 'Golfo de Fonseca',
                'nombre_en' => 'Gulf of Fonseca',
                'nombre_en' => 'Gulf of Fonseca',
                'descripcion' => 'Zona costera compartida por El Salvador, Honduras y Nicaragua, reconocida por sus paisajes marítimos e islas.',
                'descripcion_en' => 'Coastal area shared by El Salvador, Honduras, and Nicaragua, known for its maritime landscapes and islands.',
                'ubicacion' => 'La Unión',
                'ubicacion_en' => 'La Unión',
                'departamento' => 'La Unión',
                'municipio' => 'La Unión',
                'direccion' => 'Zona costera del Golfo de Fonseca, La Unión.',
                'contacto' => 'Información turística local',
                'contacto_en' => 'Local tourist information',
                'telefono' => '2600-0004',
                'sitio_web' => null,
                'imagen' => 'images/golfo_real.png',
                'costo_estimado' => 20.00,
                'dias_atencion' => 'Todos los días',
                'dias_atencion_en' => 'Every day',
                'hora_apertura' => '07:00',
                'hora_cierre' => '17:00',
                'horario' => null,
                'recomendaciones' => 'Consultar disponibilidad de recorridos en lancha y llevar protección solar.',
                'recomendaciones_en' => 'Check availability of boat tours and bring sun protection.',
                'estado' => true,
                'latitud' => 13.3369000,
                'longitud' => -87.8439000,
            ],
            [
                'categoria_id' => $recreativos?->id,
                'nombre' => 'Laguna Seca El Pacayal',
                'nombre_en' => 'Dry Lagoon El Pacayal',
                'nombre_en' => 'Dry Lagoon El Pacayal',
                'descripcion' => 'La Laguna Seca El Pacayal es un imponente destino geográfico en la cima del Volcán Chinameca, a 1,350 metros de altura. A pesar de su nombre, es una enorme caldera volcánica seca originada hace 59,000 años por una de las erupciones más potentes de Centroamérica. Hoy en día, su cráter está cubierto por cafetales y un clima fresco, ofreciendo un paisaje donde incluso se pueden observar fumarolas geotérmicas.',
                'descripcion_en' => 'Dry Lagoon El Pacayal is an imposing geographical destination at the top of the Chinameca Volcano, at an altitude of 1,350 meters. Despite its name, it is a massive dry volcanic caldera originating 59,000 years ago from one of the most powerful eruptions in Central America. Today, its crater is covered by coffee plantations and a cool climate, offering a landscape where geothermal fumaroles can even be observed.',
                'ubicacion' => 'Chinameca, San Miguel',
                'ubicacion_en' => 'Chinameca, San Miguel',
                'departamento' => 'San Miguel',
                'municipio' => 'Chinameca',
                'direccion' => 'Laguna Seca El Pacayal, Chinameca, San Miguel',
                'contacto' => 'Administración del centro recreativo',
                'contacto_en' => 'Recreation center administration',
                'telefono' => '2600-0005',
                'sitio_web' => null,
                'imagen' => 'images/pacayal_paisaje.png',
                'costo_estimado' => 0.00,
                'dias_atencion' => 'Todos los días',
                'dias_atencion_en' => 'Every day',
                'hora_apertura' => null,
                'hora_cierre' => null,
                'horario' => null,
                'recomendaciones' => 'Es indispensable el acompañamiento de un guía local. Se recomienda usar calzado con buena tracción, ropa para clima fresco y llevar abundante hidratación.',
                'recomendaciones_en' => 'It is essential to be accompanied by a local guide. It is recommended to wear footwear with good traction, clothing for cool weather, and bring plenty of hydration.',
                'estado' => true,
                'latitud' => 13.4833000,
                'longitud' => -88.1833000,
            ],
            [
                'categoria_id' => $restaurantes?->id,
                'nombre' => 'Restaurante Mirador Oriental',
                'nombre_en' => 'Mirador Oriental Restaurant',
                'nombre_en' => 'Mirador Oriental Restaurant',
                'descripcion' => 'Restaurante turístico con comida típica salvadoreña y ambiente familiar.',
                'descripcion_en' => 'Tourist restaurant with typical Salvadoran food and a family atmosphere.',
                'ubicacion' => 'San Miguel',
                'ubicacion_en' => 'San Miguel',
                'departamento' => 'San Miguel',
                'municipio' => 'San Miguel',
                'direccion' => 'Carretera Panamericana, San Miguel.',
                'contacto' => 'Atención al cliente',
                'contacto_en' => 'Customer service',
                'telefono' => '2600-0002',
                'sitio_web' => 'https://www.facebook.com/',
                'imagen' => 'images/restaurante_mirador_oriental.jpg',
                'costo_estimado' => 18.00,
                'dias_atencion' => 'Martes a domingo',
                'dias_atencion_en' => 'Tuesday to Sunday',
                'hora_apertura' => '10:00',
                'hora_cierre' => '21:00',
                'horario' => null,
                'recomendaciones' => 'Ideal para almuerzos familiares y visitantes que buscan gastronomía local.',
                'recomendaciones_en' => 'Ideal for family lunches and visitors looking for local cuisine.',
                'estado' => true,
                'latitud' => 13.4830000,
                'longitud' => -88.1750000,
            ],
            [
                'categoria_id' => $hoteles?->id,
                'nombre' => 'Hotel Vista Azul',
                'nombre_en' => 'Vista Azul Hotel',
                'nombre_en' => 'Vista Azul Hotel',
                'descripcion' => 'Hotel turístico orientado a visitantes que buscan alojamiento cerca de la playa.',
                'descripcion_en' => 'Tourist hotel aimed at visitors looking for accommodation near the beach.',
                'ubicacion' => 'El Cuco, San Miguel',
                'ubicacion_en' => 'El Cuco, San Miguel',
                'departamento' => 'San Miguel',
                'municipio' => 'Chirilagua',
                'direccion' => 'Calle principal hacia Playa El Cuco, Chirilagua.',
                'contacto' => 'Recepción del hotel',
                'contacto_en' => 'Hotel reception',
                'telefono' => '2600-0003',
                'sitio_web' => 'https://www.example.com',
                'imagen' => 'images/hotel_vista_azul.jpg',
                'costo_estimado' => 45.00,
                'dias_atencion' => 'Todos los días',
                'dias_atencion_en' => 'Every day',
                'hora_apertura' => '00:00',
                'hora_cierre' => '23:59',
                'horario' => null,
                'recomendaciones' => 'Recomendado para visitantes que desean hospedarse cerca de la playa.',
                'recomendaciones_en' => 'Recommended for visitors who want to stay near the beach.',
                'estado' => true,
                'latitud' => 13.1760000,
                'longitud' => -88.1050000,
            ],
            [
                'categoria_id' => $culturales?->id,
                'nombre' => 'Centro Histórico de Alegría',
                'nombre_en' => 'Alegría Historic Center',
                'nombre_en' => 'Alegría Historic Center',
                'descripcion' => 'Zona cultural con arquitectura tradicional, gastronomía local y espacios para recorrer en familia.',
                'descripcion_en' => 'Cultural area with traditional architecture, local gastronomy, and spaces for family tours.',
                'ubicacion' => 'Alegría, Usulután',
                'ubicacion_en' => 'Alegría, Usulután',
                'departamento' => 'Usulután',
                'municipio' => 'Alegría',
                'direccion' => 'Centro del municipio de Alegría, Usulután.',
                'contacto' => 'Casa de la cultura local',
                'contacto_en' => 'Local house of culture',
                'telefono' => '2600-0008',
                'sitio_web' => null,
                'imagen' => 'images/centro_historico_alegria.jpeg',
                'costo_estimado' => 5.00,
                'dias_atencion' => 'Todos los días',
                'dias_atencion_en' => 'Every day',
                'hora_apertura' => '08:00',
                'hora_cierre' => '18:00',
                'horario' => null,
                'recomendaciones' => 'Visitar el parque central, probar comida local y recorrer los alrededores.',
                'recomendaciones_en' => 'Visit the central park, try local food, and explore the surroundings.',
                'estado' => true,
                'latitud' => 13.5000000,
                'longitud' => -88.4833000,
            ],
            [
                'categoria_id' => $recreativos?->id,
                'nombre' => 'Hostal y Parque Acuático El Edén de Brizuela',
                'nombre_en' => 'El Edén de Brizuela Hostel and Water Park',
                'nombre_en' => 'El Edén de Brizuela Hostel and Water Park',
                'descripcion' => 'Este es uno de los destinos recreativos más recientes y populares en Nueva Guadalupe, ideal para quienes buscan refrescarse y pasar un día de relajación familiar. El lugar destaca por sus atractivas instalaciones acuáticas, que incluyen opciones para niños, una piscina semi-olímpica y la llamativa "piscina de la isla", cuyo diseño simula un pequeño montículo de tierra en el centro del agua. Además de los baños, el complejo ofrece una experiencia integral con servicio de restaurante especializado en platillos como churrascos, aves y mariscos a la plancha, área de bar, mesas de billar y espacios de descanso. Para quienes desean extender su visita, también cuenta con habitaciones de alojamiento, convirtiéndolo en un pequeño resort muy completo para los turistas.',
                'descripcion_en' => 'This is one of the most recent and popular recreational destinations in Nueva Guadalupe, ideal for those looking to cool off and spend a day of family relaxation. The place stands out for its attractive water facilities, which include options for children, a semi-olympic pool, and the striking "island pool", whose design simulates a small mound of earth in the center of the water. In addition to the bathrooms, the complex offers a comprehensive experience with a restaurant service specializing in dishes such as churrascos, poultry, and grilled seafood, a bar area, billiard tables, and resting spaces. For those who wish to extend their visit, it also has accommodation rooms, making it a very complete small resort for tourists.',
                'ubicacion' => 'Nueva Guadalupe, San Miguel',
                'ubicacion_en' => 'Nueva Guadalupe, San Miguel',
                'departamento' => 'San Miguel',
                'municipio' => 'Nueva Guadalupe',
                'direccion' => 'Nueva Guadalupe, San Miguel.',
                'contacto' => 'Administración del parque',
                'contacto_en' => 'Park administration',
                'telefono' => '2600-0000',
                'sitio_web' => null,
                'imagen' => 'images/eden_brizuela.jpg',
                'costo_estimado' => 5.00,
                'dias_atencion' => 'Todos los días',
                'dias_atencion_en' => 'Every day',
                'hora_apertura' => '09:00',
                'hora_cierre' => '20:00',
                'horario' => null,
                'recomendaciones' => 'Llevar traje de baño y ropa cómoda. Ideal para familias.',
                'recomendaciones_en' => 'Bring a swimsuit and comfortable clothes. Ideal for families.',
                'estado' => true,
                'latitud' => 13.5317600,
                'longitud' => -88.3506000,
            ],
            [
                'categoria_id' => $recreativos?->id,
                'nombre' => 'Turicentro Flor del Río',
                'nombre_en' => 'Flor del Río Tourist Center',
                'nombre_en' => 'Flor del Río Tourist Center',
                'descripcion' => 'Turicentro natural reconocido por sus refrescantes piscinas de agua de vertiente, rodeado de vegetación y espacios ideales para el descanso familiar. Es un destino popular para refrescarse durante el fin de semana.',
                'descripcion_en' => 'Natural tourist center known for its refreshing spring water pools, surrounded by vegetation and ideal spaces for family rest. It is a popular destination to cool off during the weekend.',
                'ubicacion' => 'Moncagua, San Miguel',
                'ubicacion_en' => 'Moncagua, San Miguel',
                'departamento' => 'San Miguel',
                'municipio' => 'Moncagua',
                'direccion' => 'Moncagua, San Miguel.',
                'contacto' => 'Administración del turicentro',
                'contacto_en' => 'Tourist center administration',
                'telefono' => '2600-0000',
                'sitio_web' => null,
                'imagen' => 'images/flor_del_rio.jpg',
                'costo_estimado' => 5.00,
                'dias_atencion' => 'Todos los días',
                'dias_atencion_en' => 'Every day',
                'hora_apertura' => '08:00',
                'hora_cierre' => '17:00',
                'horario' => null,
                'recomendaciones' => 'Llevar traje de baño, protector solar y ropa cómoda.',
                'recomendaciones_en' => 'Bring a swimsuit, sunscreen, and comfortable clothes.',
                'estado' => true,
                'latitud' => 13.6065700,
                'longitud' => -88.2545000,
            ],
        ];

        $destinos[] = [
            'categoria_id' => $naturaleza?->id,
            'nombre' => 'Lago de Ilopango',
            'descripcion' => 'El lago de Ilopango es un lago de origen volcánico en El Salvador. Mide 8 x 11 km, tiene una superficie de 72 km² y una profundidad de 230 m. Es el lago natural más grande de El Salvador. Sus aguas son ideales para la pesca y la navegación.',
            'ubicacion' => 'San Salvador, Cuscatlán y La Paz',
            'departamento' => 'San Salvador',
            'municipio' => 'Ilopango',
            'direccion' => 'A 16 km de la ciudad de San Salvador',
            'contacto' => 'Información turística local',
            'telefono' => '2200-0000',
            'sitio_web' => null,
            'imagen' => 'img/destinos/ilopango.jpg',
            'costo_estimado' => 5.00,
            'dias_atencion' => 'Todos los días',
            'hora_apertura' => '08:00',
            'hora_cierre' => '17:00',
            'horario' => 'Abierto de lunes a domingo de 8:00 AM a 5:00 PM',
            'recomendaciones' => 'Llevar protector solar, ropa ligera y cámara fotográfica para los hermosos paisajes de la caldera volcánica.',
            'estado' => true,
            'latitud' => 13.6703000,
            'longitud' => -89.0531000,
        ];

        foreach ($destinos as $destino) {
            Destino::updateOrCreate(
                ['nombre' => $destino['nombre']],
                $destino
            );
        }
    }
}